[custom]
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！
;视频演示规则，因为教学原因添加的类型比较全面，实际应用应尽量删减，在达到自己目的的情况下做到最简化，否则会造成网络卡顿和延迟！！！！！

;电报群：https://t.me/qichiyuchat

;规则集定义
ruleset=📹 AppleTV,https://raw.githubusercontent.com/mightyorange/public/refs/heads/main/AppleTV.list
ruleset=📹 Binance,https://raw.githubusercontent.com/mightyorange/public/refs/heads/main/Binance.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mightyorange/public/refs/heads/main/Direct.list
ruleset=🚀 世界高速,https://raw.githubusercontent.com/mightyorange/public/refs/heads/main/ProxyLite.list
ruleset=🤖 AI,https://raw.githubusercontent.com/mightyorange/public/refs/heads/main/AI.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🚀 世界高速,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 世界高速,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

;地区定义
custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(深港|US|家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇸🇬 加坡节点`select`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🥕 台湾节点`select`(?=.*(台湾|TW|Taiwan))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)

;策略组定义
custom_proxy_group=🤖 AI`url-test`(GPT|美|US|美国|United States)`http://www.gstatic.com/generate_204`300,5,100
custom_proxy_group=📹 Binance`url-test`(日本|日|JP|Japan|东京|大阪)`http://www.gstatic.com/generate_204`300,5,100
custom_proxy_group=🚀 世界高速`url-test`^((?!(倍率|0\.5|0\.5倍|0\.5x|2\.0|2倍|2x|3\.0|3倍|3x|4\.0|4倍|4x|5\.0|5倍|5x|剩余|流量|过期)).)*$`http://www.gstatic.com/generate_204`300,5,100
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 世界高速`[]DIRECT

;以下策略组为各服务指向基础策略组，方便未来精细控制
custom_proxy_group=📹 AppleTV`select`[]🚀 世界高速
custom_proxy_group=🍎 Apple`select`[]🚀 世界高速
custom_proxy_group=📲 Telegram`select`[]🚀 世界高速
custom_proxy_group=♻️ Speedtest`select`[]🚀 世界高速
custom_proxy_group=📹 YouTube`select`[]🚀 世界高速
custom_proxy_group=🎥 Netflix`select`[]🚀 世界高速
custom_proxy_group=🎵 TikTok`select`[]🥕 台湾节点
custom_proxy_group=🎞️ 国内媒体`select`[]🎯 全球直连
custom_proxy_group=🌍 国外媒体`select`[]🚀 世界高速

;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
